spring.application.name=userauth

spring.datasource.url=jdbc:mysql://localhost:3309/userauth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# no password set for local development using xampp connection

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=A3sD5fG7hJ9kL1mN4pQ6rT8uV0wX2yZ4aB6cE8gH0iK2jM4nP6qS8tU0vW2xY4zA6b
jwt.expiration-minutes=60
